<?php
$webUrl = Mage::getBaseUrl();
$skinUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
?>

<!--img src="<?php //echo $this->getSkinUrl('images/home/bestseller.jpg');?>" />-->
<!--best sellers begin-->
<div class="seller-Box clearfix">
	<div class="seller-Head">
		<h3>Best Sellers</h3>
	</div>
	<div class="seller-Main row clearfix">
		<div class="col-xs-12 col-lg-7 col-md-7 hidden-xs">
			<div class="seller-L1 left">
			<a href="<?php echo $webUrl."iphone-7-plus-lcd-black-original.html"?>">
				<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/iphone7pluslcd.jpg" alt="for iphone 7 plus lcd black original">
				<i class="imgText">LCD</i>
			</a>
			</div>
			<div class="seller-L2 left">
				<a href="<?php echo $webUrl."g-sp-samsung-s8-plus-super-glass-gold.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L2.jpg" alt=" for samsung s8 plus super glass gold">
					<i class="imgText">Glass</i>
				</a>
			</div>
		</div>
		<div class="col-xs-12 col-lg-5 col-md-5">
			<div class="seller-L3 clearfix">
				<a href="<?php echo $webUrl."for-iphone-8-lcd-display-original-new-white.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/8g002lcd.jpg" alt="for iphone 8 lcd">
					<i class="imgText it1">IC</i>
				</a>
				<a href="<?php echo $webUrl."for-iphone-8-sim-card-tray-gold.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/iphone8simcard.jpg" alt="for iphone 8 sim card">
					<i class="imgText it2">Case</i>
				</a>
				<a href="<?php echo $webUrl."for-iphone-8-8-plus-home-button-complete-gold.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/8g036homebutton.jpg" alt="for iphone 8 home button">
					<i class="imgText it3">Battery</i>
				</a>
				<a href="<?php echo $webUrl."for-iphone-8-charge-flex-black.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/8g022flexcable.jpg" alt="for iphone 8 flex cable">
					<i class="imgText it4">Flex</i>
				</a>
			</div>
		</div>
	</div>
</div>
