<?php
if(!$this->getConfig('enabled')) return;

$_productCollection=$this->getProductCollection();
$_helper = $this->helper('catalog/output');
$helpLabels = $this->helper('themevast/labels');
?>
<style>
    .qtyBox{display: inline-block;}
    .qtyBtn{display: inline-block;width: 12px;height: 20px;font-size: 14px;line-height: 16px;-webkit-appearance : none!important;border: 1px solid #a29e9e;background: #f5f5f5;border-radius: 0;}
    .qtyBtn:active{background: #bfc1c1;}
    .featuredproduct .products-grid li.item .ratings{display: none;}
</style>
<div class="featuredproduct">
	<?php echo $this->getConfig('title') ? '<div class="bx-title featured-title"><h2>' .$this->getConfig('title'). '</h2></div>' : '';
	if(!$_productCollection->count()): ?> 
		<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
	<?php else: ?>
	<?php
		// getConfig
		$widthImage  	= $this->getConfig('widthImage') ? $this->getConfig('widthImage') : 135;
		$heightImage 	= $this->getConfig('heightImage') ? $this->getConfig('heightImage') : 135;
		$price   		= $this->getConfig('price');
		$cart    		= $this->getConfig('cart');
		$compare  		= $this->getConfig('compare');
		$wishlist  		= $this->getConfig('wishlist');
		$review  		= $this->getConfig('review');
		$slide  		= $this->getConfig('slide');
		$rows 			= $this->getConfig('rows');
		$class 			= ($slide && $rows > 1) ? '.slide-multirows' : '.products-grid';
	?>
	<?php if ($slide && $rows > 1): ?>
	<div class="slide-multirows">
	<?php endif ?>
	<?php $_collectionSize = $_productCollection->count() ?>
	<?php $_columnCount = $this->getColumnCount(); ?>
	<?php $j=0; $time = $this->getConfig('playDelay'); ?>
	<?php $i=0; foreach ($_productCollection as $_product): ?>
	<?php $t = $j*$time; $t .='ms'; $j++; ?>
	<?php if ($i++%$_columnCount==0): ?>
	<ul class="products-grid">
	<?php endif ?>
		<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> item-animate">
		<div class="item-inner">
			<?php // Product Image ?>
			<div class="box-images">
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
			<?php $imagehv = $_product->load('media_gallery')->getMediaGalleryImages()->getItemByColumnValue('position','2');
				if($imagehv) : 
				$imagehv = $imagehv->getFile();
				?>
				<img class="img-face-back" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $imagehv)->resize($widthImage, $heightImage) ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			<?php endif ?>
				<img class="img-face" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($widthImage, $heightImage); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			</a>
			<a class="view-detail" <?php if(Mage::getStoreConfig('quickview/general/enabled')):?> id='fancybox<?php echo $_product->getId()?>'  href="<?php echo $this->getUrl('quickview/index/ajax',array('product_id'=>$_product->getId())); ?>"<?php else: ?> href="<?php echo $_product->getProductUrl() ?>" href="<?php echo $_product->getProductUrl() ?>" <?php endif ?> title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><i class="fa fa-search"></i></a>
			</div>
			<div class="product-shop">
				<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
				<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
				<?php if($review): ?>
					<?php echo $this->getReviewsSummaryHtml($_product) ?>
				<?php endif; ?>
				<?php if($price): ?>
					<?php echo $this->getPriceHtml($_product, true) ?>
				<?php endif; ?>
				<div class="actions">
					<?php if($cart): ?>
						<?php if($_product->isSaleable()): ?>
                            <div class="qtyBox f-left clearfix">
                                <input type="button" value="-" class="left qtyBtn qtyReduce"/>
                                <input type="number" class="act-input f-left"  value="1" oninput="if(value.length>3)value=value.slice(0,3);" onchange="if(value<1)value=1;" data-toggle="tooltip" title="qty > 0"/>
                                <input type="button" value="+" class="left qtyBtn qtyAdd"/>
                            </div>
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart f-left" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
					<?php endif; ?>
				</div>
			</div>
			<?php echo $helpLabels->getLabels($_product); //Product labels ?>
		</div>
		</li>
	<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
	</ul>
	<?php endif ?>
	<?php endforeach ?>
	<?php if ($slide && $rows > 1): ?>
	</div>
	<?php endif ?>
	<?php endif ?>
	<?php if($slide) : ?>
		<script type="text/javascript">
			jQuery(document).ready(function($){
				if($(document).width() < 767){

				}else{
				
					(function(selector){
						var $content = $(selector);
						var $slider  = $('<?php echo $class ?>', $content);
						var slider 	 = $slider.bxSlider({
							<?php echo $this->setBxslider() ?>
							//infiniteLoop: false,
							moveSlides:1,
							slideMargin: 10,
							autoHover: true, // stop while hover <=> slider.stopAuto(); + slider.startAuto();
						})
			
					})(".featuredproduct");
				}
				jQuery(".featuredproduct,.dealproducts").delegate(".qtyBtn","click",function(){
				    var $qtyBox = jQuery(this).parent();
				    var $input = $qtyBox.find(".act-input");
				    var inputVal = $input.val();
				    if(jQuery(this).hasClass("qtyReduce")&&inputVal>1){
				        inputVal--;
				        $input.val(inputVal);
                    }else if(jQuery(this).hasClass("qtyAdd")){
				        inputVal++;
				        $input.val(inputVal);
                    }
                });
			});
		</script>
	<?php endif ?>
</div>
<?php ?>
